<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8" />
        <title>Mock objects and non-existent attributes/methods in Python</title>
        <link rel="stylesheet" href="/theme/css/main.css" />
        <link href="/feeds/all.atom.xml" type="application/atom+xml" rel="alternate" title="Programming and Writing about it Atom Feed" />

        <!--[if IE]>
            <script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
</head>

<body id="index" class="home">
        <header id="banner" class="body">
                <h1><a href="/">Programming and Writing about it </a></h1>
                <nav><ul>
                    <li><a href="/pages/about.html">About</a></li>
                    <li><a href="/pages/articles.html">Articles</a></li>
                    <li><a href="/pages/books.html">Books</a></li>
                    <li><a href="/pages/personal-projects.html">Personal Projects</a></li>
                </ul></nav>
        </header><!-- /#banner -->
<section id="content" class="body">
  <article>
    <header>
      <h1 class="entry-title">
        <a href="/mock-objects-and-non-existent-attributesmethods-in-python.html" rel="bookmark"
           title="Permalink to Mock objects and non-existent attributes/methods in Python">Mock objects and non-existent attributes/methods in Python</a></h1>
<a href="https://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="echorand">Tweet</a><script type="text/javascript" src="https://platform.twitter.com/widgets.js"></script>
    </header>

    <div class="entry-content">
<footer class="post-info">
        <abbr class="published" title="2016-01-11T14:00:00+10:00">
                Published: Mon 11 January 2016
        </abbr>

        <address class="vcard author">
                By                         <a class="url fn" href="/author/amit-saha.html">Amit Saha</a>
        </address>
<p>In <a href="/category/python.html">Python</a>.</p>

</footer><!-- /.post-info -->      <p><em>Updated</em>: Fixed typo in the last paragraph.</p>
<p>Today, I was curious to see this behavior of <tt class="docutils literal">Mock()</tt> objects when using <a class="reference external" href="https://github.com/testing-cabal/mock">mock</a>:</p>
<pre class="code literal-block">
&gt;&gt;&gt; from mock import Mock
&gt;&gt;&gt; m = Mock()
&gt;&gt;&gt; m.i_dont_exist
&lt;Mock name='mock.i_dont_exist' id='139841609578768'&gt;
&gt;&gt;&gt; m.i_dont_exist()
&lt;Mock name='mock.i_dont_exist()' id='139841609106896'&gt;
</pre>
<p>The above is expected, since I have not declared a spec when creating the <tt class="docutils literal">Mock()</tt> object, so even when you call a non-existent method or get/set a non-existent attribute, you will not get a <tt class="docutils literal">AttributeError</tt>.</p>
<p>However, I was suprised by the following:</p>
<pre class="code literal-block">
&gt;&gt;&gt; m.assert_not_calledd
Traceback (most recent call last):
 File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
File &quot;/home/asaha/.local/share/virtualenvs/606fc8723c1a01b/lib/python2.7/site-packages/mock/mock.py&quot;, line 721, in _    _getattr__
   raise AttributeError(name)
 AttributeError: assert_not_calledd
</pre>
<p>And the following as well:</p>
<pre class="code literal-block">
&gt;&gt;&gt; m.assert_foo
Traceback (most recent call last):
File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
File &quot;/home/asaha/.local/share/virtualenvs/606fc8723c1a01b/lib/python2.7/site-packages/mock/mock.py&quot;, line 721, in __getattr__
  raise AttributeError(name)
  AttributeError: assert_foo
</pre>
<p>I guessed that there is likely a check explicitly for <strong>non-existent
attributes</strong> starting with <tt class="docutils literal">assert</tt>, and if it finds so, it will
raise a <tt class="docutils literal">AttributeError</tt>.  If you look at the <a class="reference external" href="https://github.com/testing-cabal/mock/blob/master/mock/mock.py#L708">__getattr__</a>
method in <tt class="docutils literal">mock.py</tt>, you will see that this is pretty much what is
happening. The exact lines are below:</p>
<pre class="code literal-block">
if not self._mock_unsafe: # self._mock_unsafe is by default False
    if name.startswith(('assert', 'assret')): # It comes here and an AttributeError is raised
        raise AttributeError(name)
</pre>
<p>This is certainly a good thing, since I have often seen
<a class="reference external" href="http://engineeringblog.yelp.com/2015/02/assert_called_once-threat-or-menace.html">assert_called_once</a>
in codebases, and is fairly easy to overlook.</p>

    </div><!-- /.entry-content -->

  </article>
</section>
        <section id="extras" class="body">
                <div class="social">
                        <h2>social</h2>
                        <ul>
                            <li><a href="/feeds/all.atom.xml" type="application/atom+xml" rel="alternate">atom feed</a></li>

                        </ul>
                </div><!-- /.social -->
        </section><!-- /#extras -->

        <footer id="contentinfo" class="body">
                <address id="about" class="vcard body">
                Proudly powered by <a href="http://getpelican.com/">Pelican</a>, which takes great advantage of <a href="http://python.org">Python</a>.
                </address><!-- /#about -->

                <p>The theme is by <a href="http://coding.smashingmagazine.com/2009/08/04/designing-a-html-5-layout-from-scratch/">Smashing Magazine</a>, thanks!</p>
        </footer><!-- /#contentinfo -->

</body>
</html>